### ISSUE TITLE
After run 10 days, my iRedMail in Docker appear a error "warning: connect to TCP map 127.0.0.1:7778: Connection refused" and can't accept any SMTP request

### ISSUE THREAD

**Issue by bi7jta** [iredmail/dockerized#114]
Hi,
anyone can help me ? thank you.
I almost try any possible reasons and answers from Google search , kill and rm the docker container, but no help and not solve my problem .

So I just reinstall the docker container again, remove MySQL data , maybe can help.

I have guess the system debian Insufficient memory, only 1GB.

**
root@mail:/# /etc/init.d/clamav-daemon restart
 * Stopping ClamAV daemon clamd                [ OK ]
 * Starting ClamAV daemon clamd           Killed     [fail]                    
**

 root@mail:/# /etc/init.d/amavis restart
 Stopping amavisd: amavisd-new.
 Starting amavisd: amavisd-new.

apt-get update;
apt-get install net-tools
netstat -ntlp
root@mail:/# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:24              0.0.0.0:*               LISTEN      743/dovecot
tcp        0      0 0.0.0.0:25              0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:12346           0.0.0.0:*               LISTEN      743/dovecot
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      752/nginx: master p
tcp        0      0 0.0.0.0:4190            0.0.0.0:*               LISTEN      743/dovecot
tcp        0      0 0.0.0.0:993             0.0.0.0:*               LISTEN      743/dovecot
tcp        0      0 0.0.0.0:995             0.0.0.0:*               LISTEN      743/dovecot
tcp        0      0 0.0.0.0:10024           0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:10025         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      751/php-fpm: master
tcp        0      0 0.0.0.0:10026           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:10027           0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:10028         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:9998            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:110             0.0.0.0:*               LISTEN      743/dovecot
tcp        0      0 127.0.0.1:7790          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:143             0.0.0.0:*               LISTEN      743/dovecot
tcp        0      0 127.0.0.1:7791          0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      752/nginx: master p
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:24242           0.0.0.0:*               LISTEN      743/dovecot
tcp        0      0 0.0.0.0:12340           0.0.0.0:*               LISTEN      743/dovecot

Aug 22 03:34:02 mail postfix/pickup[926]: 4M9ydQ6gD2zsSS6: uid=0 from=<root>
Aug 22 03:34:02 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:03 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:04 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:05 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:06 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:07 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:08 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:09 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:10 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:11 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:11 mail postfix/cleanup[927]: warning: tcp:127.0.0.1:7778 lookup error for "root@mail.xxx.org"
Aug 22 03:34:11 mail postfix/cleanup[927]: warning: 4M9ydQ6gD2zsSS6: sender_canonical_maps map lookup problem for root@mail.xxxx.org -- message not accepted, try again later
Aug 22 03:34:11 mail postfix/pickup[926]: warning: maildrop/4M9jDT6yTTzsRLg: error writing 4M9ydQ6gD2zsSS6: queue file write error
Aug 22 03:34:11 mail postfix/pickup[926]: 4M9ydb6k38zsSS6: uid

=0 from=<root>
Aug 22 03:34:11 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:12 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:13 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused
Aug 22 03:34:14 mail postfix/cleanup[927]: warning: connect to TCP map 127.0.0.1:7778: Connection refused

![iRedMail-7778-cannot-connect](https://user-images.githubusercontent.com/22002824/185834046-b05dc017-dac2-4d11-bb56-57529d6bc7e6.png)

**Comment by iredmail** [comment]
> I have guess the system debian Insufficient memory, only 1GB.

- iRedMail requires at least 4GB memory, mostly used by SpamAssassin and ClamAV for spam/virus scanning.
- Port 7778 is handled by iRedAPD service, please check its log file to check why it failed to start. Also `/var/log/syslog`.
