### ISSUE TITLE
jammy build will break roundcube

### ISSUE THREAD

**Issue by fleek** [iredmail/dockerized#115]
jammy will install php8.1-fpm by default whiles the configuration in roundcube still uses php7.4-fpm.  Solution is to add ppa source to the script and install php7.4-fpm and php7.4-cli instead of php-fpm and php-cli.

**Comment by iredmail** [comment]
jammy should use Roundcube 1.6.0 instead, better wait for next release which contains many PHP8 compatibility issues fixed.

**Comment by fleek** [comment]
I am running the container on a raspberry pi4 and have successfully built the image for arm64 after adding the php ppa and changing the packages to the exact php7.4-fpm and php7.4-cli.  I will reverse out my temporary fix when the new version comes.
