### ISSUE TITLE
Use own maria db 

### ISSUE THREAD

**Issue by durduliu2009** [iredmail/dockerized#12]
Hello,

I saw that this package comes with everything which is great but if I have my own maria db which I want to be used by this product înstead maintaining 2 dbs is there some settings to make ? 

Also you advise us not to use it in production ( yet ). When we will be able to use it as production grade ? 
Many thanks in advance

**Comment by iredmail** [comment]
- It will be hard to handle SQL related changes/update with a remote/separate mariadb server. So, no plan to support it (yet).
- Still lack of Let's Encrypt cert support.

Feedbacks, contributions are always welcome. Send PRs to help improve it. :)

**Comment by richie-tt** [comment]
also I am looking for such setup
