### ISSUE TITLE
MariaDB lost settings ? 

### ISSUE THREAD

**Issue by ricristian** [iredmail/dockerized#13]
Hello,

I've started working with latest nightly docker tag, I've maded steps described in documentation everything was working perfectly .. but after Ive made a few docker stop iredmail && docker start iredmail .. I saw that some erros occurs in docker logs 

docker logs --follow iredmail

```root@2q1e:~# docker logs --follow iredmail
[iRedMail] [Entrypoint] /docker/entrypoints/mariadb.sh 
[iRedMail] Starting temporary MariaDB instance.
2020-06-02 23:45:51 0 [Note] mysqld (mysqld 10.4.13-MariaDB-log) starting as process 164 ...
[iRedMail] Reset password for SQL user 'root'.
[iRedMail] [Run] /docker/mariadb/pre_start/0-vmail_db.sh
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'vmail'@'%'
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'vmailadmin'@'%'
[iRedMail] Grant privileges to SQL user 'vmail' and 'vmailadmin'.
[iRedMail] Make sure postmaster@domain-name.com is a global admin.
[iRedMail] [Run] /docker/mariadb/pre_start/amavisd_db.sh
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'amavisd'@'%'
[iRedMail] [Run] /docker/mariadb/pre_start/fail2ban_db.sh
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'fail2ban'@'%'
[iRedMail] [Run] /docker/mariadb/pre_start/iredadmin_db.sh
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'iredadmin'@'%'
[iRedMail] [Run] /docker/mariadb/pre_start/iredapd_db.sh
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'iredapd'@'%'
[iRedMail] [Run] /docker/mariadb/pre_start/roundcube.sh
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'roundcube'@'%'
[iRedMail] [Run] /docker/mariadb/pre_start/sa_bayes.sh
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'sa_bayes'@'%'
[iRedMail] [Entrypoint] /docker/entrypoints/dovecot.sh 
[iRedMail] Generating self-signed ssl cert under /opt/iredmail/ssl.
Generating a RSA private key
......++++
.................................................................................................................................................++++
writing new private key to '/opt/iredmail/ssl/key.pem'
-----
[iRedMail] Generating dh param file: /opt/iredmail/ssl/dhparam2048.pem. It make take a long time.
Generating DH parameters, 2048 bit long safe prime, generator 2
This is going to take a long time
....................................................................+.......................................................+................+.........................................................................................+.................................................................................+..........................+........................................................................+.........................................+............................................................+................+.........................................................................+.........................................................................................+......................................................................................+.................+............................+..................................................................................................................................................................+..............................+..............................................................+..................+.....+.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................+....................+....................................................................+.....................................................................+.........................+...........................................................+......................................................+........................................................................................................+.....................................................................................................................................................................................................................................................................................+.......................................+............+...........................................................+........................................................................................................................................................................................................+.......................................................................................................+......+..........+..........................+...........................................................+.........................+..+....................................................................................................................................................................................................+...................................+......................................................................................................................................+..........+.................+.....................................................+..............+....................................................................................................................................................................................+.....................................................................................................................................+........................................................................................................................+................+...+..............+....................................+........+.........................+.....................................+.......................................+.....................+................................................................................................+..........................................................+.......................................................................................+................................+...................................................................+..................................................................................................................+............................................................+....................................................................................................+....................................................................................+..............................+............................................................................................................................+................................................................+.................+.......................................................................................................................+.......................................................................................................................................................................................................................................................................................+....................................................................................................................................................................................+.............+.........................................+...........................+.......................+.................................................................+...............................................+...............................................................................................................................................+...................+..............+....+................+......................................................................................................................................................................................+................+..............+.+.....................................................+..+.........................................................................+......................................................+...................................................................................................................................................................+...+...........................................+.......................................................+................++*++*++*++*
[iRedMail] [Entrypoint] /docker/entrypoints/postfix.sh 
Generating DH parameters, 512 bit long safe prime, generator 2
This is going to take a long time
..+.....+..........+.......+.................+....+.....+........+............++*++*++*++*++*
[iRedMail] [Entrypoint] /docker/entrypoints/mlmmj.sh 
[iRedMail] [Entrypoint] /docker/entrypoints/mlmmjadmin.sh 
[iRedMail] [Entrypoint] /docker/entrypoints/iredapd.sh 
[iRedMail] [Entrypoint] /docker/entrypoints/antispam.sh 
[iRedMail] Run 'sa-update' (required by Amavisd).
Update finished, no fresh updates were available
[iRedMail] [Entrypoint] /docker/entrypoints/nginx.sh 
[iRedMail] [Entrypoint] /docker/entrypoints/phpfpm.sh 
[iRedMail] [Entrypoint] /docker/entrypoints/roundcube.sh 
[iRedMail] [Entrypoint] /docker/entrypoints/fail2ban.sh 
[iRedMail] [Entrypoint] /docker/entrypoints/iredadmin.sh 
[iRedMail] CMD: /usr/bin/supervisord -c /etc/supervisord.
```

Also i tried to look in /var/lib/mysql from container to see if there are files and it seems ok 

```/var/lib/mysql # ls -als
total 188704
     4 drwxr-xr-x   11 mysql    root          4096 Jun  3 10:51 .
     8 drwxr-xr-x    1 root     root          4096 Jun  2 23:46 ..
     4 drwx------    2 mysql    mysql         4096 Jun  2 23:25 amavisd
    68 -rw-rw----    1 mysql    mysql        65536 Jun  3 10:55 aria_log.00000001
     4 -rw-rw----    1 mysql    mysql           52 Jun  3 10:51 aria_log_control
     4 drwx------    2 mysql    mysql         4096 Jun  2 23:25 fail2ban
     8 -rw-r-----    1 mysql    mysql         4114 Jun  3 10:51 ib_buffer_pool
 49152 -rw-rw----    1 mysql    mysql     50331648 Jun  3 10:55 ib_logfile0
 49152 -rw-rw----    1 mysql    mysql     50331648 Jun  2 23:25 ib_logfile1
 77824 -rw-rw----    1 mysql    mysql     79691776 Jun  3 10:55 ibdata1
 12288 -rw-rw----    1 mysql    mysql     12582912 Jun  3 10:51 ibtmp1
     4 drwx------    2 mysql    mysql         4096 Jun  2 23:25 iredadmin
     4 drwx------    2 mysql    mysql         4096 Jun  2 23:25 iredapd
     0 -rw-rw----    1 mysql    mysql            0 Jun  2 23:25 multi-master.info
     4 drwx------    2 mysql    mysql         4096 Jun  2 23:25 mysql
    68 -rw-rw----    1 mysql    mysql        61981 Jun  3 10:57 mysqld.err
     4 drwx------    2 mysql    mysql         4096 Jun  2 23:25 performance_schema
     4 drwx------    2 mysql    mysql         4096 Jun  2 23:25 roundcubemail
     4 drwx------    2 mysql    mysql         4096 Jun  2 23:25 sa_bayes
    92 -rw-rw----    1 mysql    mysql        87682 Jun  3 10:51 slow-query.log
     4 drwx------    2 mysql    mysql         4096 Jun  2 23:25 vmail
```

**Comment by iredmail** [comment]
> ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist

Anything changed during stop and restart? IP address?

**Comment by durduliu2009** [comment]
Nope, nothing.

**Comment by iredmail** [comment]
hmm, i didn't experience this error before, no clue right now. :(

Did you restore the databases?

**Comment by durduliu2009** [comment]
Nope nothing ... Instead I saw something weird regarding cron jobs but this is another topic and I will come back with more details after I will make more debugging. 

As for maria db since I don't have any backup ... probabil I will try to reinitiate the whole process since now I have that ansible role

**Comment by iredmail** [comment]
Try to reproduce the issue steadily, it will help figure out the root cause and hopefully fix it.

**Comment by durduliu2009** [comment]
Ok,
So i've created an folder called iredmail under / -> final result /iredmail
under this /iredmail folder I will have docker-iredmail.conf

```
root@2q1e:/iredmail# tree -d 
.
`-- data
    |-- backup
    |-- clamav
    |   `-- tmp
    |-- custom
    |   |-- amavisd
    |   |   `-- dkim
    |   |-- dovecot
    |   |   `-- conf-enabled
    |   |-- iredapd
    |   |-- mlmmjadmin
    |   |-- mysql
    |   |-- postfix
    |   |   `-- disclaimer
    |   |-- roundcube
    |   `-- spamassassin
    |-- imapsieve_copy
    |-- mailboxes
    |-- mlmmj
    |-- mlmmj-archive
    |-- mysql
    |   |-- amavisd
    |   |-- fail2ban
    |   |-- iredadmin
    |   |-- iredapd
    |   |-- mysql
    |   |-- performance_schema
    |   |-- roundcubemail
    |   |-- sa_bayes
    |   `-- vmail
    |-- postfix_queue
    |   `-- etc
    |-- sa_rules
    |   `-- 3.004003
    |       `-- updates_spamassassin_org
    `-- ssl

36 directories
```

Which seems ok ... ( all subfolders where created by image tag: nightly )
I've started the container -> OK ( all logs seems to be ok roundcube is working and so on ) 
If I will hit `docker stop iredmail && docker start iredmail && docker logs --follow iredmail` than game is over and errors that I;ve shown earlier comes up and roundcube webpage will show ```DATABASE ERROR: CONNECTION FAILED!
Unable to connect to the database!
Please contact your server-administrator.```

**Comment by iredmail** [comment]
Seems `docker start iredmail` loses all environment variables, there's no relations between your iredmail container and data under `/iredmail/` directory.

**Comment by durduliu2009** [comment]
I'm not that sure because if i will check environments variables from container with
`docker exec -it iredmail sh` and then `env` I will see variables from iredmail-docker.config 
```
HOSTNAME=mail.domain-name.com
SHLVL=1
HOME=/root
FIRST_MAIL_DOMAIN=domain-name.com
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ROUNDCUBE_DES_KEY=72neDbKMUfkoMvncqoe0OKy6jeSV5Rlc
FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=FaxewEJDJ1DRugn6qIwQtZ9haON2BU9vhgqCTn6+XQE=
PWD=/
MLMMJADMIN_API_TOKEN=FaxewEJDJ1DRugn6qIwQtZ9haON2BU9vhgqCTn6+XQE=
```

**Comment by iredmail** [comment]
> I've removed volume attachment for myql in order to see if data will persist in container directly without volume which docker start / stop should still keep data but unfortunately same errors

What does this mean? You removed the volume used to store MySQL databases and start the container?

**Comment by ricristian** [comment]
I've made again same steps except mounting mysql volume. In case of start stop docker container won't lose data. ( In our case mysql should'nt lose settings but unfortunately it seems that db loses data)

**Comment by iredmail** [comment]
- In this all-in-one container, you should NOT run script under `/docker/entrypoints/` separately. 
- The logic is defined in script `/entrypoint.sh`, it reads few other scripts.

**Comment by iredmail** [comment]
Please record the steps you ran to reproduce the issue, so that others can reproduce and help test and fix it.

**Comment by ricristian** [comment]
In order not to waste time by writing each step I've recorded my screen with steps ... 
https://www.youtube.com/watch?v=gWowzbRoWGg

**Comment by iredmail** [comment]
Thanks for the video, but it doesn't help much.
I need a step-by-step instruction to reproduce the issue, which includes:

- How you initial the docker (first run)
- How you get this issue after first run

So that i can reproduce the issue locally and hopefully fix it.

**Comment by ricristian** [comment]
I'm not sure that I understand. In video is shown that it is a clear environment without any iredmail folder /  configuration. 
That ansible will so everything and then after start stop docker variables from dockerized config are duplicated. There is no docker process issues or something like that.

**Comment by iredmail** [comment]
Oops, my mistake.
Can you reproduce this issue if you pull/run the image manually (instead of deploying with Ansible)? Just want to make sure it's not an issue of your Ansible code.

**Comment by iredmail** [comment]
Any update?

**Comment by bsglinux16** [comment]
i get the same mariadb error too
I couldn't find a solution, it prevents sending e-mails
The command I use is:
docker run \
    --name iredmail \
    --env-file iredmail-docker.conf \
    --hostname roundcube.over-click.codes \
    -p 1010:80 \
    -p 1011:443 \
    -p 110:110 \
    -p 995:995 \
    -p 143:143 \
    -p 993:993 \
    -p 25:25 \
    -p 465:465 \
    -p 587:587 \
    -v /iredmail/data/backup:/var/vmail/backup \
    -v /iredmail/data/mailboxes:/var/vmail/vmail1 \
    -v /iredmail/data/mlmmj:/var/vmail/mlmmj \
    -v /iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive \
    -v /iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy \
    -v /iredmail/data/custom:/opt/iredmail/custom \
    -v /iredmail/data/ssl:/opt/iredmail/ssl \
    -v /iredmail/data/mysql:/var/lib/mysql \
    -v /iredmail/data/clamav:/var/lib/clamav \
    -v /iredmail/data/sa_rules:/var/lib/spamassassin \
    iredmail/mariadb:nightly

**Comment by bsglinux16** [comment]
Fix the error please

**Comment by iredmail** [comment]
@bsglinux16 whats the error message?

**Comment by bsglinux16** [comment]
[iRedMail] Create directory used to store custom config files: /opt/iredmail/custom/mysql.
[iRedMail] Initializing database ...
[iRedMail] Starting temporary MariaDB instance.
2020-06-23 14:13:56 0 [Note] mysqld (mysqld 10.4.13-MariaDB-log) starting as process 233 ...
[iRedMail] Create MariaDB root user.
[iRedMail] [Run] /docker/mariadb/pre_start/0-vmail_db.sh
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
[iRedMail] Create database 'vmail' and tables.
[iRedMail] Grant privileges to SQL user 'vmail' and 'vmailadmin'.
[iRedMail] Create first mail domain: over-click.codes.
[iRedMail] Add user postmaster@over-click.codes.
[iRedMail] Add (internal) mail forwarding for postmaster@over-click.codes.
[iRedMail] Make sure postmaster@over-click.codes is a global admin.
[iRedMail] [Run] /docker/mariadb/pre_start/amavisd_db.sh
[iRedMail] + Create database amavisd.
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
[iRedMail] + Create default spam policy.
[iRedMail] [Run] /docker/mariadb/pre_start/fail2ban_db.sh
[iRedMail] + Create database fail2ban.
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
[iRedMail] [Run] /docker/mariadb/pre_start/iredadmin_db.sh
[iRedMail] + Create database iredadmin.
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
[iRedMail] [Run] /docker/mariadb/pre_start/iredapd_db.sh
[iRedMail] + Create database iredapd.
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**

**Comment by bsglinux16** [comment]
it continues with errors like this
I can't send mail when I enter the panel after the installation is over

**Comment by iredmail** [comment]
@bsglinux16  Which Linux host OS and release are you running?

**Comment by iredmail** [comment]
@bsglinux16 is it possible for you to try it with a Ubuntu 18.04 machine?

**Comment by bsglinux16** [comment]
I can open a temporary Ubuntu Server 18.04
I will throw the result to you

**Comment by bsglinux16** [comment]
[iRedMail] Create directory used to store custom config files: /opt/iredmail/custom/mysql.
[iRedMail] Initializing database ...
[iRedMail] Starting temporary MariaDB instance.
2020-06-23 14:26:52 0 [Note] mysqld (mysqld 10.4.13-MariaDB-log) starting as process 232 ...
[iRedMail] Create MariaDB root user.
[iRedMail] [Run] /docker/mariadb/pre_start/0-vmail_db.sh
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
[iRedMail] Create database 'vmail' and tables.
[iRedMail] Grant privileges to SQL user 'vmail' and 'vmailadmin'.
[iRedMail] Create first mail domain: over-click.codes.
[iRedMail] Add user postmaster@over-click.codes.
[iRedMail] Add (internal) mail forwarding for postmaster@over-click.codes.
[iRedMail] Make sure postmaster@over-click.codes is a global admin.
[iRedMail] [Run] /docker/mariadb/pre_start/amavisd_db.sh
[iRedMail] + Create database amavisd.
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
[iRedMail] + Create default spam policy.
[iRedMail] [Run] /docker/mariadb/pre_start/fail2ban_db.sh
[iRedMail] + Create database fail2ban.
ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
[iRedMail] [Run] /docker/mariadb/pre_start/iredadmin_db.sh
[iRedMail] + Create database iredadmin.
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
[iRedMail] [Run] /docker/mariadb/pre_start/iredapd_db.sh
[iRedMail] + Create database iredapd.
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
[iRedMail] + Enable greylisting.
[iRedMail] [Run] /docker/mariadb/pre_start/roundcube.sh
[iRedMail] + Import /opt/www/roundcubemail/SQL/mysql.initial.sql
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
[iRedMail] [Run] /docker/mariadb/pre_start/sa_bayes.sh
[iRedMail] + Create database sa_bayes.
[iRedMail] + Import sa_bayes.mysql
**ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist**
.......

**Comment by bsglinux16** [comment]
It's the same on every server again
Cannot Send Emails
Stuck on "Sending Message"

**Comment by bsglinux16** [comment]
> I'm not that sure because if i will check environments variables from container with
> `docker exec -it iredmail sh` and then `env` I will see variables from iredmail-docker.config
> 
> ```
> HOSTNAME=mail.domain-name.com
> SHLVL=1
> HOME=/root
> FIRST_MAIL_DOMAIN=domain-name.com
> TERM=xterm
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> ROUNDCUBE_DES_KEY=72neDbKMUfkoMvncqoe0OKy6jeSV5Rlc
> FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=FaxewEJDJ1DRugn6qIwQtZ9haON2BU9vhgqCTn6+XQE=
> PWD=/
> MLMMJADMIN_API_TOKEN=FaxewEJDJ1DRugn6qIwQtZ9haON2BU9vhgqCTn6+XQE=
> ```
> 
> I've removed volume attachment for myql in order to see if data will persist in container directly without volume which docker start / stop should still keep data but unfortunately same errors
> 
> ```
> iRedMail] [Entrypoint] /docker/entrypoints/mariadb.sh 
> [iRedMail] Starting temporary MariaDB instance.
> 2020-06-03 21:06:17 0 [Note] mysqld (mysqld 10.4.13-MariaDB-log) starting as process 236 ...
> [iRedMail] Reset password for SQL user 'root'.
> [iRedMail] [Run] /docker/mariadb/pre_start/0-vmail_db.sh
> ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
> ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'vmail'@'%'
> ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
> ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'vmailadmin'@'%'
> [iRedMail] Grant privileges to SQL user 'vmail' and 'vmailadmin'.
> [iRedMail] Make sure postmaster@domain-name.com is a global admin.
> [iRedMail] [Run] /docker/mariadb/pre_start/amavisd_db.sh
> ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
> ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'amavisd'@'%'
> [iRedMail] [Run] /docker/mariadb/pre_start/fail2ban_db.sh
> ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
> ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'fail2ban'@'%'
> [iRedMail] [Run] /docker/mariadb/pre_start/iredadmin_db.sh
> ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
> ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'iredadmin'@'%'
> [iRedMail] [Run] /docker/mariadb/pre_start/iredapd_db.sh
> ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
> ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'iredapd'@'%'
> [iRedMail] [Run] /docker/mariadb/pre_start/roundcube.sh
> ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
> ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'roundcube'@'%'
> ERROR: SQLSTATE[HY000] [1045] Access denied for user 'roundcube'@'localhost' (using password: YES)
> ERROR: Failed to connect to database
> [iRedMail] [Run] /docker/mariadb/pre_start/sa_bayes.sh
> ERROR 1449 (HY000) at line 1: The user specified as a definer ('mariadb.sys'@'localhost') does not exist
> ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'sa_bayes'@'%'
> [iRedMail] [Entrypoint] /docker/entrypoints/dovecot.sh 
> ln: /etc/dovecot/conf-enabled/service-imap-hibernate.conf: File exists
> ln: /etc/dovecot/conf-enabled/stats.conf: File exists
> [iRedMail] [Entrypoint] /docker/entrypoints/postfix.sh 
> [iRedMail] [Entrypoint] /docker/entrypoints/mlmmj.sh 
> [iRedMail] [Entrypoint] /docker/entrypoints/mlmmjadmin.sh 
> [iRedMail] [Entrypoint] /docker/entrypoints/iredapd.sh 
> [iRedMail] [Entrypoint] /docker/entrypoints/antispam.sh 
> [iRedMail] Run 'sa-update' (required by Amavisd).
> Update finished, no fresh updates were available
> [iRedMail] [Entrypoint] /docker/entrypoints/nginx.sh 
> [iRedMail] [Entrypoint] /docker/entrypoints/phpfpm.sh 
> [iRedMail] [Entrypoint] /docker/entrypoints/roundcube.sh 
> [iRedMail] [Entrypoint] /docker/entrypoints/fail2ban.sh 
> [iRedMail] [Entrypoint] /docker/entrypoints/iredadmin.sh 
> [iRedMail] CMD: /usr/bin/supervisord -c /etc/supervisord.conf
> ```

If I don't use the --rm parameter, I get the same error with this friend in my 2nd opening

**Comment by bsglinux16** [comment]
Please Help

**Comment by iredmail** [comment]
Hi @bsglinux16 @ricristian 

All issues have been fixed. Could you please try again?

**Comment by bsglinux16** [comment]
Thanks Mysql Errors Fixed
Throws Roundcube Mail
But Emails Do Not Come To Inbox Or Spam
I think the problem may be due to Roundcube

**Comment by iredmail** [comment]
Any error in log files listed below?

- `/var/log/roundcube/roundcube.log`
- `/var/log/dovecot/dovecot.log` and `imap.log`

I pushed a new fix moment ago, could you please try the latest Docker image?

**Comment by iredmail** [comment]
Closed due to no further update. Feel free to create a new issue.
