### ISSUE TITLE
Why the docker hub iredmail stable image is so old?

### ISSUE THREAD

**Issue by ghevge** [iredmail/dockerized#138]
I am interested in deploying iredmail instance on a dockerize system, but lookign at the dockerhub available tags, I've notices that the stable image tag is 2 years old. A bit too old IMO judging on the iredmail fequency of releases.

https://hub.docker.com/r/iredmail/mariadb/tags

Any chance to get more frequent tags on dockerhub? Also any changes to tag the versions too, not just the latest.

Thanks

**Comment by iredmail** [comment]
The problem with old stable is we have to maintain 2 separate code for deployment / installation. The new one[1] uses same deployment code and more flexible, so we will focus on the new one in the future. It's still in public beta and not ready for production yet.

[1] the new one: https://hub.docker.com/r/iredmail/test-mariadb

**Comment by ghevge** [comment]
This answer sounds discuriging. I don't see why you would want/need to have 2 separate codes for deployment / installation plus 2+ years is a very long period, more than enough to come up with a  stabile doker image, task that IMO should not take more than 1-2 days. Anyway thanks for your answer, I will give a second though if I will want to go with iredmail or choose another email server.
