### ISSUE TITLE
password

### ISSUE THREAD

**Issue by iomari** [iredmail/dockerized#139]
Greeting, I just installed with the docker image. What is the name/pasword for the iredadmin?

**Comment by maartenvr98** [comment]
As you can see here https://github.com/iredmail/dockerized#required-parameters you need to set a first domain and password. With that password you can login in Roundcube with postmaster@yourdomain.com and the password set during the initial setup. 

Once logged in you'll receive a mail with the all the information you need to continue your setup.

**Comment by iomari** [comment]
Thanks
