### ISSUE TITLE
SMTP Smuggling

### ISSUE THREAD

**Issue by BigBrainAFK** [iredmail/dockerized#146]
Will the docker image be updated to mitigate a recent issue of SMTP smuggling?
If not at least some documentation on how to update this for the more uninitiated might be nice.

[Documentation of SMTP Smuggling](https://www.postfix.org/smtp-smuggling.html)

**Comment by iredmail** [comment]
Document is available here:
https://docs.iredmail.org/upgrade.iredmail.1.6.7-1.6.8.html#mitigate-postfix-smtp-smuggling-attack-short-term-workaround

**Comment by BigBrainAFK** [comment]
While this works fine for the normal iredmail installation this wouldn't work on docker as the postfix configuration is not stored on the host. The readme of the docker repo needs to be updated to reflect some changes in my opinion. I personally just copied the entire `/etc/postfix` folder out of a running docker instance of iredmail, made the changed to main.cf manually and then mounted it into the docker image so that the config persists between restores.

I may misunderstand how iredmail stores the changes and it could be that they can somehow be kept between docker container restarts/destroys without storing the files on the host system.
