### ISSUE TITLE
Container crashes with a mysqld bus error at startup

### ISSUE THREAD

**Issue by 112batman** [iredmail/dockerized#15]
This is my startup command: 
`
docker run --rm --name iredmail --hostname mail.hoftijzer.tk -p 80:80 -p 433:433 -p 110:110 -p 995:995 -p 143:143 -p 993:993 -p 25:25 -p 465:465 -p 587:587 -v /home/pi/data/backup:/var/vmail/backup -v /home/pi/data/mailboxes:/var/vmail/vmail1 -v /home/pi/data/mlmmj:/var/vmail/mlmmj -v /home/pi/data/mlmmj-archive:/var/vmail/mlmmj-archive -v /home/pi/data/imapsieve_copy:/var/vmail/imapsieve_copy -v /home/pi/data/costum:/opt/iredmail/costum -v /home/pi/data/ssl:/opt/iredmail/ssl -v /home/pi/data/mysql:/var/lib/mysql -v /home/pi/data/clamav:/var/lib/clamav -v /home/pi/data/sa_rules:/var/lib/spamassassin -v /home/pi/data/postfix_queue:/var/spool/postfix --env-file iredmail-docker.conf iredmail/mariadb:nightly
`

I followed the instructions exactly just modified some paths

This is the error output:
`
[iRedMail] [Entrypoint] /docker/entrypoints/mariadb.sh
[iRedMail] Create directory used to store custom config files: /opt/iredmail/custom/mysql.
[iRedMail] Starting temporary MariaDB instance.
2020-06-25 15:41:04 0 [Note] /usr/bin/mysqld (mysqld 10.4.13-MariaDB-log) starting as process 433 ...
/docker/entrypoints/mariadb.sh: line 65:   433 Bus error               mysqld ${cmd_mysqld_opts}
[iRedMail] Initialization failed. Please check /var/lib/mysql/mysqld.err for more details.
`

Any help?

**Comment by iredmail** [comment]
No clue. Does it work fine if you use directories outside /home for volumes?

**Comment by 112batman** [comment]
Gonna check

**Comment by 112batman** [comment]
No, using directories /home doesn't work.

Output: 
`
[iRedMail] [Entrypoint] /docker/entrypoints/mariadb.sh
[iRedMail] Create directory used to store custom config files: /opt/iredmail/custom/mysql.
[iRedMail] Starting temporary MariaDB instance.
2020-06-25 16:23:28 0 [Note] /usr/bin/mysqld (mysqld 10.4.13-MariaDB-log) starting as process 432 ...
/docker/entrypoints/mariadb.sh: line 65:   432 Bus error               mysqld ${cmd_mysqld_opts}
[iRedMail] Initialization failed. Please check /var/lib/mysql/mysqld.err for more details.
`

Start command used:
`
docker run --rm --name iredmail --hostname mail.hoftijzer.tk -p 80:80 -p 433:433 -p 110:110 -p 995:995 -p 143:143 -p 993:993 -p 25:25 -p 465:465 -p 587:587 -v /iredmail/data/backup:/var/vmail/backup -v /iredmail/data/mailboxes:/var/vmail/vmail1 -v /iredmail/data/mlmmj:/var/vmail/mlmmj -v /iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive -v /iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy -v /iredmail/data/costum:/opt/iredmail/costum -v /iredmail/data/ssl:/opt/iredmail/ssl -v /iredmail/data/mysql:/var/lib/mysql -v /iredmail/data/clamav:/var/lib/clamav -v /iredmail/data/sa_rules:/var/lib/spamassassin -v /iredmail/data/postfix_queue:/var/spool/postfix --env-file iredmail-docker.conf iredmail/mariadb:nightly
`

**Comment by iredmail** [comment]
- Which linux distribution and release are you running?
- Which docker release?

**Comment by 112batman** [comment]
Output from uname -a:
`
Linux [domain] 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
`
I am running the latest release of raspberry pi os lite (32-bit)

Output from docker --version:
`
Docker version 19.03.12, build 48a6621
`

**Comment by iredmail** [comment]
We didn’t test RPi before. Is it possible for you to try it on another (non-RPi) machine?

**Comment by 112batman** [comment]
I could start a VM to test, wich OS should I try it on?

**Comment by 112batman** [comment]
It does work on a debian 10 64-bit VM
