### ISSUE TITLE
[CRITICAL][SECURITY] Bad config networks

### ISSUE THREAD

**Issue by ThibaultPelloquin** [iredmail/dockerized#16]
Hi!

There is an important security issue in the config files.

postfix trusts all IPs ranges from `mynetworks` config value.

You added `172.0.0.0/8` range in the list, which means that anyone with a `172.*` IP address can send emails by simply attacking the host server.

The only range to use is `172.16.0.0/12` (which represents [private network](https://en.wikipedia.org/wiki/Private_network#Private_IPv4_addresses) from `172.16.0.0` to `172.31.255.255`)

I take this issue to inform you I would have prefered sending it to you by email, but no security contact form is available on iredmail.org. 😔

**Comment by ThibaultPelloquin** [comment]
Hi

Sorry to come back, but the security issue is real, and it makes the entire stack unusable. :(

**Comment by iredmail** [comment]
These IP addresses were used for my own testing purpose in iRedMail Easy ansible code, but forgot to remove them after testing. Sorry about this.
