### ISSUE TITLE
clamav (exit status 1; not expected)

### ISSUE THREAD

**Issue by arbermejo0417** [iredmail/dockerized#20]
Hi, i'm trying to deploy the iredmail docker container as described in the docs but it crashes when trying to deploy ClamAV with the following errors

INFO spawned: 'clamav' with pid 13565
INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
INFO exited: clamav (exit status 1; not expected)

**Comment by iredmail** [comment]
- Any clamav virus signature database files in `/var/lib/clamav`?
- While launching the container, did you see "freshclam" command finished correctly?

**Comment by iredmail** [comment]
Closed due to no further update.
