### ISSUE TITLE
execvp /usr/bin/mlmmj-amime-receive: No such file or directory

### ISSUE THREAD

**Issue by tensor5g** [iredmail/dockerized#29]
I get this error when trying to email a mailing list I created with maillist_admin.py

> 2020-11-20T23:54:48.086404+00:00 mail postfix/amavis/smtp[22917]: 4CdD1M5l4Nz1R09: to=<dl-veeam@(domain)>, relay=127.0.0.1[127.0.0.1]:10026, delay=0.29, delays=0.05/0/0/0.24, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 4CdD1N0Jz4z1R0D)
2020-11-20T23:54:48.088523+00:00 mail postfix/pipe[22974]: fatal: pipe_command: execvp /usr/bin/mlmmj-amime-receive: No such file or directory
2020-11-20T23:54:48.099569+00:00 mail postfix/qmgr[1165]: 4CdD1M5l4Nz1R09: removed
2020-11-20T23:54:48.105731+00:00 mail postfix/pipe[22973]: 4CdD1N0Jz4z1R0D: to=<dl-veeam@(domain)>, relay=mlmmj, delay=0.06, delays=0.03/0.01/0/0.02, dsn=4.3.0, status=deferred (temporary failure. Command output: pipe: fatal: pipe_command: execvp /usr/bin/mlmmj-amime-receive: No such file or directory )

These are the contents of /usr/bin/mlm*
> /usr/bin/mlmmj-list
/usr/bin/mlmmj-maintd
/usr/bin/mlmmj-make-ml
/usr/bin/mlmmj-make-ml.sh -> mlmmj-make-ml
/usr/bin/mlmmj-process
/usr/bin/mlmmj-receive
/usr/bin/mlmmj-recieve -> mlmmj-receive
/usr/bin/mlmmj-send
/usr/bin/mlmmj-sub
/usr/bin/mlmmj-unsub

I am using the iredmail/mariadb:stable image

**Comment by iredmail** [comment]
Thanks for the report.
That file was missing and fixed in latest commit. New `nightly` and `stable` builds are available for testing.

**Comment by tensor5g** [comment]
The file is there now, but I am getting new errors. 

2020-11-21T16:54:15.823286+00:00 mail postfix/pipe[1293]: 4Cdfdg4WJMz1RCq: to=<dl-veeam@(domain)>, relay=mlmmj, delay=0.19, delays=0.15/0.01/0/0.04, dsn=4.3.0, status=deferred (temporary failure. Command output: pipe: fatal: pipe_command: execvp /usr/bin/mlmmj-amime-receive: Permission denied )

**Comment by iredmail** [comment]
Fixed in latest nightly build. Could you please give it a try?

**Comment by tensor5g** [comment]
I am getting this error now

> 2020-11-22T03:37:11.629323+00:00 mail mlmmj-amime-receive: Email was not successfully sent (without footer).
2020-11-22T03:37:11.629511+00:00 mail postfix/pipe[1377]: 4CdwvW4FCSz1RM8: to=<dl-veeam@(domain)>, relay=mlmmj, delay=0.03, delays=0.01/0.01/0/0.01, dsn=2.0.0, status=sent (delivered via mlmmj service (Have to invoke either as root or as the user owning listdir))

**Comment by iredmail** [comment]
Could you try to create a new mailing list and send email to it for testing?

**Comment by tensor5g** [comment]
Same error after creating a new one.

**Comment by iredmail** [comment]
It works fine for me. How did you create the mailing list?
FYI: https://docs.iredmail.org/manage.subscribeable.mailing.lists.html

**Comment by tensor5g** [comment]
python3 maillist_admin.py create list@domain.com
python3 maillist_admin.py add_subscribers list@domain.com email1 email2

Any options I need to set? I want anyone to be able to email it

**Comment by iredmail** [comment]
> `python3 maillist_admin.py create [list@domain.com](mailto:list@domain.com)`
> `python3 maillist_admin.py add_subscribers [list@domain.com](mailto:list@domain.com) email1 email2`

Commands are correct.

> Any options I need to set? I want anyone to be able to email it

You must set both `only_moderator_can_post` and `only_subscriber_can_post` to `no` like this:

```
python3 maillist_admin.py update list@domain.com only_moderator_can_post=no only_subscriber_can_post=no
```

Default setting is `only_subscriber_can_post=yes`.

Questions for you:

- Is directory /var/vmail/mlmmj itself and all files/directories under it owned by `mlmmj:mlmmj` user/group?
- Did the subscribers receive the testing email you sent?
- Please show us full Postfix log lines for troubleshooting if there's any error or unexpected behaviour.

**Comment by tensor5g** [comment]
> Is directory /var/vmail/mlmmj itself and all files/directories under it owned by mlmmj:mlmmj user/group?

/var/vmail/mlmmj is, but my domain and all files underneath are root:mlmmj

After correcting this with chown -R mlmmj:mlmmj /var/vmail/mlmmj/(domain) it is now working as intended. 

However, if I create a new group the permissions again default to root:mlmmj for the new mailing list. The docker volume storing mlmmj is on an NFS share, so perhaps that's why it has this odd behavior? I use a lot of other docker containers on the share and they don't have the problem. Perhaps maillist_admin.py could be modified to ensure correct permissions are set after create is run?

**Comment by iredmail** [comment]
The owner was set while creating list, I guess it’s more about the NFS storage, but I don’t have a NFS for testing right now. 

You may need to check mount options on NFS server and client sides.
