### ISSUE TITLE
clavmav exit status 1 cycling

### ISSUE THREAD

**Issue by brentwmyers** [iredmail/dockerized#31]
When running docker with volumes, after entering `docker run` with all of the flags, this are starting up, most services are spawned, then there is a continuous cycle of:
`2020-11-29 23:08:39,502 INFO exited: clamav (exit status 1; not expected)
2020-11-29 23:08:40,509 INFO spawned: 'clamav' with pid 888
2020-11-29 23:08:40,540 INFO success: clamav entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
`
I've tried a few things but to no avail. Any pointers?

**Comment by iredmail** [comment]
Please login to the container and check log files under /var/log/, we need related log for troubleshooting.

**Comment by brentwmyers** [comment]
I'll likely get to this next weekend.

**Comment by ted423** [comment]
ipv4 network,but 
```
downloadFile: Download destination: /var/lib/clamav/tmp.f004c89a4d/clamav-b8296cde8e43dd7ed2e2913c548cff17.tmp
*   Trying 104.16.219.84:443...
* TCP_NODELAY set
*   Trying 2606:4700::6810:da54:443...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700::6810:da54: Cannot assign requested address
*   Trying 2606:4700::6810:db54:443...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700::6810:db54: Cannot assign requested address
*   Trying 2606:4700::6810:da54:443...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700::6810:da54: Cannot assign requested address
*   Trying 2606:4700::6810:db54:443...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700::6810:db54: Cannot assign requested address
*   Trying 2606:4700::6810:da54:443...
* TCP_NODELAY set
* Immediate connect fail for 2606:4700::6810:da54: Cannot assign requested address
*   Trying 2606:4700::6810:db54:443...
```

**Comment by iredmail** [comment]
> * Immediate connect fail for 2606:4700::6810:db54: Cannot assign requested address

Seems your docker environment issue?

**Comment by ted423** [comment]
> > * Immediate connect fail for 2606:4700::6810:db54: Cannot assign requested address
> 
> Seems your docker environment issue?

set
    --sysctl net.ipv6.conf.all.disable_ipv6=1 \
seems not work
