### ISSUE TITLE
Disable: Redirect all insecure http:// requests to https:// 

### ISSUE THREAD

**Issue by jcalfee** [iredmail/dockerized#34]
I would like to disable the re-direct on port 80 so I can use it unencrypted.  I already have SSL configured in a reverse proxy pointed to this container.  Is there something I can do in data/custom/nginx/sites-enabled that might make this work, perhaps I need to setup an additional port?  What do you recommend?

https://github.com/iredmail/dockerized/blob/4bd5112277ef5846d7b169cba6d7a3e23ffb84c8/config/etc/nginx/sites-available/00-default.conf#L14-L15

**Comment by OlJohnny** [comment]
If you are using a reverse proxy in front of the iredmail docker container, you can just point the reverse proxy to the encrypted port.
I am also using a reverse proxy, and it works for me.

From my <code>docker-compose.yml</code>:
<pre>ports:
      - 8820:443</pre>

From my nginx config:
<pre>server {
    listen 443 ssl http2;
    server_name mail.example.com;
    location / {
        proxy_pass https://127.0.0.1:8820;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host      $host;
    }
}</pre>

**Comment by smooker** [comment]
How this helps for the reverse https proxy ?
