### ISSUE TITLE
postfix not using correct letsencrypt certificate

### ISSUE THREAD

**Issue by tensor5g** [iredmail/dockerized#36]
Postfix is configured to use the /opt/iredmail/ssl/cert.pem certificate no matter what. However, letsencrypt needs to use combined.pem to prevent certificate errors. I can manually edit /etc/postfix/main.cf but this will break after every update, and I don't believe there is a way to create custom postfix config files.

**Comment by iredmail** [comment]
- Use `/opt/iredmail/custom/postfix/custom.sh` to modify Postfix configurations with `postconf` command.
- You should link letsencrypt cert to `/opt/iredmail/ssl/cert.pem` (and `key.pem`, `combined.pem`). I suggest link `fullchain.pem` to BOTH `cert.pem` and `combined.pem`.
