### ISSUE TITLE
Docker-compose build issue. Smth with add_user_vmail.sh

### ISSUE THREAD

**Issue by LisichkinVlad** [iredmail/dockerized#38]
Last commit 809fb00.

Clone repo and try to `docker-compose up --build`.
Output:
`: not foundipts/add_user_vmail.sh: line 3:`
`: not foundipts/add_user_vmail.sh: line 8:`
`addgroup: illegal character with code 13 at position 5`
`adduser: illegal character with code 13 at position 5`
`ERROR: Service 'iredmail_dovecot' failed to build: The command '/bin/sh -c /bin/sh ${SCRIPTS_DIR}/add_user_vmail.sh &&     rm -rf ${SCRIPTS_DIR}' returned a non-zero code: 1`.

Also, I dont understand volumes in docker-compose.yml. Where are their mountpoints? They include envs, for example `${DOCKER_VOLUME_CUSTOM_CONF_DIR}`, but I didnt found, where this envs set?

**Comment by LisichkinVlad** [comment]
For those, who want to just run the app, checkout to stable tag `git checkout stable` or use CLI. This issue is just information to developers.

**Comment by iredmail** [comment]
Please use the all-in-one container instead, docker-compose edition is not yet working and probably won’t be improved.
