### ISSUE TITLE
Failing to store banned IP addresses in SQL database

### ISSUE THREAD

**Issue by andre-sam** [iredmail/dockerized#41]
Fail2ban is unable to update MySQL database, logs are showing "ERROR Failed to execute ban jail 'postfix-pregreet' action 'banned_db' info 'ActionInfo..."

This sees to be related to the current permissions set for /opt/iredmail/bin/fail2ban/banned_db and /opt/iredmail/bin/fail2ban/unbanip

Applying "chmod 0550" to both files fixed the problem.

I am using the stable version, "iredmail/mariadb:stable"

**Comment by iredmail** [comment]
Fixed in latest commit (nightly build). Thanks for the feedback. :)
