### ISSUE TITLE
WIP: Moving from Alpine to Ubuntu (20.04, focal)

### ISSUE THREAD

**Issue by iredmail** [iredmail/dockerized#43]
Dear all,

We're moving the base image from Alpine to Ubuntu (20.04, focal), the latest nightly build might not work during the transition. We need help to test it as much as possible to make it stable.

## Known issues

- [x] MySQL failed to start if relaunch container
- [x] iRedAPD log doesn't redirect to `/var/log/iredapd/iredapd.log`. KNOWN ISSUE BUT NO PLAN TO FIX IT. iRedAPD runs with `--foreground` argument, it logs to stdout instead of syslog, so `/etc/rsyslog.d/1-iredmail-iredapd.log` is useless.
- [x] Reset MySQL root password failed:
```
ERROR 1396 (HY000) at line 2: Operation ALTER USER failed for 'root'@'%'
```

**Comment by GemzzK** [comment]
I tried to launch this container but getting these errors

![image](https://user-images.githubusercontent.com/67978637/106627375-5bf39580-653e-11eb-8a9b-9c6a77b18359.png)

**Comment by iredmail** [comment]
@GemzzK Seems your directory on host OS for mysql data directory `/var/lib/mysql` has permission issue. Could you please double check? Or use docker volume instead.

**Comment by GemzzK** [comment]
Creating volume resolved the issue. Now, Roundcube is not responding, nginx showing page not found but iredadmin is responding.

**Comment by iredmail** [comment]
@GemzzK Roundcube issue has been fixed moment ago, you can try the latest nightly build.

**Comment by GemzzK** [comment]
Roundcube is working now but now if we try to send email its showing SMTP authentication failed.

**Comment by iredmail** [comment]
Dear @GemzzK 

SMTP auth issue has been fixed with the latest nightly build (please wait for few minutes until Docker Hub finished the build).
Thank you very much for the feedback. :)
