### ISSUE TITLE
Missing pieces in quick start for newbies

### ISSUE THREAD

**Issue by bluepuma77** [iredmail/dockerized#44]
First of all thank you very much for providing this easy containerised solution.

Today I gave it a shot, but for a first time user some bits in the documentation could be improved:

1. How do I administer iredmail? "Installed softwares" lists "iRedAdmin", but it's not in "Exposed network ports".

2. Any idea of hardware requirements? What's a good starting point for number of CPUs and amount of RAM?

3. Maybe add a link to the other required piece of work: [DNS, etc.](https://docs.iredmail.org/setup.dns.html)

4. Why are two long docker commands included? I love them, but I desperately tried to find a difference ;-)

5. I find this way of generating the environment file a bit easier to read:
```
cat << EOF > iredmail-docker.conf
HOSTNAME=mail.mydomain.com
FIRST_MAIL_DOMAIN=mydomain.com
FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=my-secret-password
MLMMJADMIN_API_TOKEN=$(openssl rand -base64 32)
ROUNDCUBE_DES_KEY=$(openssl rand -base64 24)
EOF
```

Cheers
bluepuma

**Comment by bluepuma77** [comment]
In the mean time I found some of the answers myself:

1. Access `iRedAdmin` at https://FIRST_MAIL_DOMAIN/iredadmin. It does not use a separate port.
Create a dmarc@your-domain.com email address for later use.

2. Just the basic installation uses 2GB RAM after initial setup. I will try with 4GB RAM and 2 vCPUs.

3. Follow [DNS setup](https://docs.iredmail.org/setup.dns.html) to avoid being classified as spam:
        1. DNS A record
        2. Reverse PTR / DNS
        3. MX record
        4. SPF record (enter without quotation marks)
        5. DKIM record (docker exec iredmail amavisd -c /etc/amavisd.conf showkeys)
        6. DMARC record (use DNS TXT record "_dmarc")

Test the "Spammyness" of emails with a service like [Mail-Tester](https://www.mail-tester.com/). But despite a perfect 10/10 score Microsoft Office365 places my emails in spam.

Reference: I found this [LinuxBabe tutorial](https://www.linuxbabe.com/mail-server/ubuntu-20-04-iredmail-server-installation) very helpful.

**Comment by iredmail** [comment]
> 2. Any idea of hardware requirements? What's a good starting point for number of CPUs and amount of RAM?

Updated document and mentions this in README.md: "at least 4GB RAM is required for a low traffic production mail server."

> 3. Maybe add a link to the other required piece of work: [DNS, etc.](https://docs.iredmail.org/setup.dns.html)

Added.

> 4. Why are two long docker commands included? I love them, but I desperately tried to find a difference ;-)

Sometimes mounting local directories inside container may have permission issue, but volume works fine. And volume is required (by MariaDB) on Windows & macOS.

> 5. I find this way of generating the environment file a bit easier to read:

This is personal favor. :)
