### ISSUE TITLE
How to save SMTP-sent emails to "Sent" folder and persist rule? (dovecot/sieve)

### ISSUE THREAD

**Issue by bluepuma77** [iredmail/dockerized#45]
Many users are asking on the web how to save sent emails automatically to a "Sent" folder. This seems usually be done by the mail client with access to the mailbox via IMAP/POP3. But how can this be done if emails are sent via plain SMTP only?

My Internet research came up with many different options, none spelled out completely. It seems `postfix` is not the right point for action, but rather `dovecot/sieve`? Will an email go through `dovecot/sieve` if it is sent from an iRedMail user via SMTP to an external party?

When I want to create a custom `dovecot/sieve` script for all users, what is the best way to persist it over container rebuilds? With another volume for a dedicated path or file?

I would try a script along those lines, I just need to find a variable that contains the current mailbox email address:
```
require "fileinto";
if address :is "from" "me@domain.tld"  {
        fileinto "Sent";
}
```

Thanks
bluepuma

**Comment by iredmail** [comment]
Use sender bcc.

**Comment by bluepuma77** [comment]
@iredmail To sort the BCC emails in my mailbox to the "Sent" folder, wouldn't it require `dovecot/sieve` again?

**Comment by iredmail** [comment]
FYI: https://docs.iredmail.org/monitor.incoming.and.outgoing.mails.with.bcc.html

sieve is involved for local delivery, SMTP don’t involve sieve at all.
