### ISSUE TITLE
Using letsencrypt for https?

### ISSUE THREAD

**Issue by bluepuma77** [iredmail/dockerized#56]
With a fresh iredmail install my browser warns me of the custom https certificate from Domzale, SI !?

Can iredmail/dockerized just use [letsencrypt](https://letsencrypt.org/) instead? The container uses nginx, there is an [article](https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/) about the process.

Projects like [acme.sh](https://github.com/acmesh-official/acme.sh), [simp_le](https://github.com/zenhack/simp_le) and [nginx-proxy/acme-companion](https://github.com/nginx-proxy/acme-companion) might be a good starting points.

**Comment by iredmail** [comment]
It's good to offer the letsencrypt integration. PR is welcome. :)

**Comment by iredmail** [comment]
SSL cert/key are stored under `/opt/iredmail/ssl/`, maybe you can mount it to another directory which contains your own valid cert/key?

**Comment by Scottpedia** [comment]
Oh yeah just got the problem resolved.

I mounted the directory on the host machine that contains my custom certificates onto `/opt/iredmail/ssl` and the programs switched to using them. Thank you for your response.

**Comment by Scottpedia** [comment]
@iredmail 
Is there a way to disable the use of ssl encryption by the webmail and webadmin portal in the dockerized iredmail suite? I am hosting several independent docker-based services on the dedicated server, many of which use port 80 to server web content. Therefore, I want to install nginx on the native host OS as the reverse proxy for all these services, such that users can access all these services under a single domain name. However, the iredmail docker container uses ssl by default and redirects all requests automatically to port 443, preventing the setup like I mentioned on the host OS.

**Comment by Scottpedia** [comment]
Is there a way to modify the nginx configuration files such that the ssl for the web apps(i.e. roundcube and iredadmin) can be disabled in the container?

**Comment by iredmail** [comment]
> Is there a way to modify the nginx configuration files such that the ssl for the web apps(i.e. roundcube and iredadmin) can be disabled in the container?

Two solutions:

- Write your own nginx config files and mount it while launching container.
- Override nginx config files with the solution mentioned in our "Best Practice" tutorial: https://docs.iredmail.org/iredmail-easy.best.practice.html
