### ISSUE TITLE
clamav (exit status 1; not expected) 

### ISSUE THREAD

**Issue by qwehua-github** [iredmail/dockerized#57]
I deploy the service according to the document, but this error keeps recurring

**Comment by iredmail** [comment]
Did command 'freshclam' finished successfully?

**Comment by qwehua-github** [comment]
[iredmail.log](https://github.com/iredmail/dockerized/files/6396180/iredmail.log)
docker run log

**Comment by qwehua-github** [comment]
docker run \
    --rm \
    --name iredmail \
    -u root \
    --privileged \
    --env-file iredmail-docker.conf \
    --hostname mail.dingxin.com \
    -p 8080:80 \
    -p 443:443 \
    -p 110:110 \
    -p 995:995 \
    -p 143:143 \
    -p 993:993 \
    -p 225:25 \
    -p 465:465 \
    -p 587:587 \
    -v /data/iredmail/data/backup:/var/vmail/backup \
    -v /data/iredmail/data/mailboxes:/var/vmail/vmail1 \
    -v /data/iredmail/data/mlmmj:/var/vmail/mlmmj \
    -v /data/iredmail/data/mlmmj-archive:/var/vmail/mlmmj-archive \
    -v /data/iredmail/data/imapsieve_copy:/var/vmail/imapsieve_copy \
    -v /data/iredmail/data/custom:/opt/iredmail/custom \
    -v /data/iredmail/data/ssl:/opt/iredmail/ssl \
    -v /data/iredmail/data/mysql:/var/lib/mysql \
    -v /data/iredmail/data/clamav:/var/lib/clamav \
    -v /data/iredmail/data/sa_rules:/var/lib/spamassassin \
    -v /data/iredmail/data/postfix_queue:/var/spool/postfix \
    iredmail/mariadb:stable

**Comment by qwehua-github** [comment]
echo HOSTNAME=mail.dingxin.com >> iredmail-docker.conf
echo FIRST_MAIL_DOMAIN=dingxin.com >> iredmail-docker.conf
echo MYSQL_ROOT_PASSWORD=iredmail@2021314 >> iredmail-docker.conf
echo FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=iredmail@2021314 >> iredmail-docker.conf
echo MLMMJADMIN_API_TOKEN=$(openssl rand -base64 32) >> iredmail-docker.conf
echo ROUNDCUBE_DES_KEY=$(openssl rand -base64 24) >> iredmail-docker.conf

**Comment by qwehua-github** [comment]
> Did command 'freshclam' finished successfully?

![image](https://user-images.githubusercontent.com/54147382/116499954-05e58280-a8e0-11eb-9d14-42943e502d8a.png)
I try to copy the local / var / spool / postfix / * to data / postfix_ queue to solve the "dovecot exit state"

**Comment by iredmail** [comment]
Any related error in /var/log/*?

**Comment by qwehua-github** [comment]
can i deploy iredmail with offline?

**Comment by iredmail** [comment]
- SpamAssassin needs to update rules regularly.
- ClamAV updates its database regularly.

If you want to run iRedMail offline, you have to disable them.
