### ISSUE TITLE
Mail after each restart

### ISSUE THREAD

**Issue by mibuthu** [iredmail/dockerized#59]
After each restart of the container I get the following mail:

> config: created user preferences file: /var/lib/amavis/.spamassassin/user_prefs

Not a big issue, but it would be a nice improvement to avoid this mail.

**Comment by iredmail** [comment]
Better mount `/var/lib/amavis` to a volume (or directory).
Could you help test it first? I will update document later.

**Comment by mibuthu** [comment]
I tested with mounting /var/lib/amavis to a directory (like all the other mounts).
But this does not work for me, I get the following error mails then:
> config: cannot create user preferences file /var/lib/amavis/.spamassassin/user_prefs: No such file or directory
> config: failed to create default user preference file /var/lib/amavis/.spamassassin/user_prefs

The mounted directory is empty, so it must be a problem with permissions.

**Comment by iredmail** [comment]
User `amavis` must have read+write privilege on this directory.

**Comment by mibuthu** [comment]
I have already tried that:
`chown 112:116 volumes/amavis`

I the container the directory settings are shown correctly then:

> $ ls -la /var/lib/amavis
> drwxr-xr-x 2 amavis amavis 4096 May  9 09:36 .
> drwxr-xr-x 1 root   root   4096 Apr 20 18:07 ..

But without success, no files are created.

**Comment by iredmail** [comment]
In the container, can you switch to `amavis` user and try to create an empty file under `/var/lib/amavis`? Any error?

**Comment by mibuthu** [comment]
Really strange. I tried several times before without any luck.
Now I have tried again to test your instructions and it is working now without any problem. I do not know what has changed.

Nevertheless the required amavis previleg change for this directory should be done during the startup phase of the container, so that no manual action is required.

**Comment by iredmail** [comment]
The permission should be set already, check line 34-41 here:
https://github.com/iredmail/dockerized/blob/master/entrypoints/antispam.sh#L34-L41

`AMAVISD_SPOOL_DIR ` is `/var/lib/amavis` (on Debian/Ubuntu).
