### ISSUE TITLE
nginx conf  port error

### ISSUE THREAD

**Issue by jinleileiking** [iredmail/dockerized#61]
if you change the   443 port, there wiil be a problem:

301 use :   Location: https://x.x.x.x/       can not use the https port you set.

**Comment by jinleileiking** [comment]
00-default.conf  

  `return 301 https://$host$request_uri;`  here should set the port passed by cmdline

**Comment by iredmail** [comment]
你是说改成类似 `return ... https://$host:4443$request_uri`?

**Comment by jinleileiking** [comment]
> 你是说改成类似 `return ... https://$host:4443$request_uri`?

是的，这个4443 应该是命令行传进来的

**Comment by iredmail** [comment]
具体怎么从命令行传入？是通过专门的 env 变量，还是指定端口映射的 `-p 443:443` 参数？

**Comment by jinleileiking** [comment]
我用的是这个：`-p 8443:443`

**Comment by jinleileiking** [comment]
应改为： https://$host:8443$request_uri

**Comment by iredmail** [comment]
> 我用的是这个：`-p 8443:443`

- 这里指定的端口号要如何在脚本里获取？似乎没有办法。
- 可行的办法是额外指定一个环境变量，例如： `docker run ... -e port_https=8443 ...`

**Comment by jinleileiking** [comment]
https://stackoverflow.com/questions/24962921/how-do-i-know-mapped-port-of-host-from-docker-container

好像只能这么处理了。。。。

**Comment by iredmail** [comment]
刚提交了改动支持命令行指定 `PORT_HTTPS` 参数了。这是个可选参数，默认使用 https 的 `443` 端口。
请帮忙测试。

**Comment by jinleileiking** [comment]
@iredmail  测了，好使
