### ISSUE TITLE
[feature] Add tools into docker image

### ISSUE THREAD

**Issue by jinleileiking** [iredmail/dockerized#64]
Add iredmail tools dir to dockerfile.
It is useful

**Comment by iredmail** [comment]
Which files/scripts (under `tools/`) do you need?

**Comment by jinleileiking** [comment]
I need  `./create_mail_user_SQL.sh`  this depends on `davoadmin` which is in docker not my laptop

**Comment by jinleileiking** [comment]
I currently clone the src in docker for running this script

**Comment by iredmail** [comment]
It's `/opt/iredmail/bin/create_user`.
