### ISSUE TITLE
How to install custom plugins in roundcube?

### ISSUE THREAD

**Issue by ryan77627** [iredmail/dockerized#65]
I was wondering how to add plugins to Roundcube. I have added the necessary files under my `custom/roundcube/plugins` directory, but have no way to add the plugin to the config.inc.php plugins parameter. How can i get iRedMail to include it?

I have tried restarting the container to see if it would rebuild with it in, but it did not. I'm not sure if that's something wrong on my end or not.

What is the proper way to enable plugins?

**Comment by iredmail** [comment]
Declare parameter `$config['plugins']` in `/opt/iredmail/custom/roundcube/custom.inc.php`, it will override the one in `/opt/www/roundcubemail/config/config.inc.php`. For example:

```
$config['plugins'] = array('managesieve', 'password', 'markasjunk', 'my-plugin-1', 'my-plugin-2');
```

**Comment by ryan77627** [comment]
Thank you!
