### ISSUE TITLE
Disable Antispam but keep DKIM

### ISSUE THREAD

**Issue by DrPepperG** [iredmail/dockerized#66]
Is there a way I can disable the antispam/antivirus but keep amavisd DKIM enabled?
I'm extremely new to docker so if there is a way to do it, please let me know.
If it is not already a feature that would be pretty handy to implement.

**Comment by iredmail** [comment]
Add lines below in `/opt/iredmail/custom/amavisd/amavisd.conf` to disable spam/virus scanning:

```
@bypass_virus_checks_maps = 1;
@bypass_spam_checks_maps = 1;
```

Note: As mentioned in our instruction (`README.md` in this repo), `/opt/iredmail/custom` should be a mounted volume, so this setting will be kept after re-launch container.
