### ISSUE TITLE
Updating the stable image from 1.2 to 1.3 has mysqld errors

### ISSUE THREAD

**Issue by thepra** [iredmail/dockerized#67]
Following is the log of the failing mysqld container which seems to have some permission issue on creating files:

> Jul 16 07:53:08 void docker[1215839]: [iRedMail] Starting temporary MariaDB instance.
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [Note] mysqld (mysqld 10.3.25-MariaDB-0ubuntu0.20.04.1-log) starting as process 210 ...
Jul 16 07:53:08 void docker[1215839]: mysqld: Can't create file '/var/lib/mysql/mysqld.err' (errno: 13 "Permission denied")
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] mysqld: File '/var/lib/mysql/aria_log_control' not found (Errcode: 13 "Permission denied")
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] Plugin 'Aria' init function returned error.
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [Note] InnoDB: Using Linux native AIO
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] Plugin 'InnoDB' init function returned error.
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [Note] Plugin 'FEEDBACK' is disabled.
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] mysqld: File '/var/lib/mysql/slow-query.log' not found (Errcode: 13 "Permission denied")
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] Could not use /var/lib/mysql/slow-query.log for logging (error 13). Turning logging off for the whole duration of the Mar>
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] Unknown/unsupported storage engine: InnoDB
Jul 16 07:53:08 void docker[1215839]: 2021-07-16  7:53:08 0 [ERROR] Aborting
Jul 16 07:53:09 void docker[1215839]: Warning: Memory not freed: 520
Jul 16 07:53:09 void systemd-networkd[488519]: veth0e2a104: Gained IPv6LL

Just before this I did this:

1. `systemctl stop iredmail.service` (when on stop runs simply `docker stop iredmail`)
2. `docker pull iredmail/mariadb:stable` and this went well without any issue
3. `systemctl start iredmail.service` which does simply `docker run...` of the usual command and parameters

What I could do to fix those permissions issue of `mysqld`? Should I delete anything from `data` to make it work?

**Comment by iredmail** [comment]
> Jul 16 07:53:08 void docker[1215839]: 2021-07-16 7:53:08 0 [ERROR] InnoDB: The innodb_system data file 'ibdata1' must be writable

Seems a file permission issue?

**Comment by thepra** [comment]
I looked up that file in the `/iredmail/data/mysql` and it does have the following permissions/ownership:
![immagine](https://user-images.githubusercontent.com/7032509/125958961-8d69cc76-ed8e-4324-86f1-ed1fc8c1357a.png)

between 1.2 and 1.3 is there some change that requires different permissions or ownership?

**Comment by iredmail** [comment]
It should be owned by MySQL daemon user/group.

**Comment by thepra** [comment]
Mmmm, I just deleted everything in data and made a clean start and indeed the permission is different right now on the same file, which isn't even the mysql one:
![immagine](https://user-images.githubusercontent.com/7032509/126007675-3102efe0-9119-4656-836f-5eccd63d361c.png)
so the upgrade from 1.2 to 1.3 entails different automatic permissions on mysql files too.
So I'm closing because I did a clean up of data, something unreasonable for other more active email servers.

**Comment by iredmail** [comment]
You should login to the container and check owner/permission, not check on the docker host.
