### ISSUE TITLE
nightly db backups broken

### ISSUE THREAD

**Issue by OliverPA77** [iredmail/dockerized#70]
/var/vmail/backup/backup_mysql.sh is referenced in crontab to perform nightly db backups and is copied via "COPY ./config/. /".
But /var/vmail/backup is mounted as a volume so once the container is up the backup script is no longer available and replaced by the content of data/backup.

I could push a PR if you want, where backup_mysql.sh is moved to scripts/mariadb ending up within the container in /docker/scripts/mariadb.

**Comment by iredmail** [comment]
I prefer using the same paths as the standard iRedMail installer and iRedMail Easy. How about we update tutorial and ask users to mount `/var/vmail/backup/mysql/` instead?

**Comment by OliverPA77** [comment]
Good idea and much simpler
