### ISSUE TITLE
'server size' customization

### ISSUE THREAD

**Issue by OliverPA77** [iredmail/dockerized#74]
Naturally a home user will have very different needs to a business user when it comes to number of processes created by nginx and php-fpm.
Would you be interested in a PR that allows customizing a few parameters controlling allocated resources?

Currently I have two ways of controlling it:
a) via env variable SERVER_SIZE set to XS, S, M, L with M being default. This in turn sets the parameters below to different values.
b) via settings env variables directly controlling nginx/php-fpm process parameters:
- NGINX_PROCESSES
- NGINX_CONNECTIONS
- FPM_MAXCHILDREN
- FPM_STARTSERVERS
- FPM_MINSPARESERVERS
- FPM_MAXSPARESERVERS

I guess mariadb and some of the other components could benefit from similar parameters but I'm not as familiar with configuring its resource allocation.

The changes to the config files are done by entrypoints/nginx.sh and entrypoints/phpfpm.sh as this allows changing the configs without rebuilding the container.

Of course clamav is the big memory hog for small/private users... Although I'm thinking about USE_CLAMAV_SERVICE=NO and then using [manual scanning](https://forum.iredmail.org/topic13607-a-solution-to-clamav-consuming-too-much-memory.html) but clamscan disappears in the container.

What do you think & any other ideas?

**Comment by iredmail** [comment]
Did you try this "Best Practice" tutorial?
https://docs.iredmail.org/iredmail-easy.best.practice.html

It's for server deployed with our iRedMail Easy platform, but this docker edition is built with iRedMail Easy too, so they share the same practice (except the docker part).

To be honest i have no interest to customize settings with many environment variables.
