### ISSUE TITLE
SMTP Relay settings

### ISSUE THREAD

**Issue by Woodie-07** [iredmail/dockerized#75]
Hello, I want to set up SMTP relay but the file that I need to change says 'please do __NOT__ modify it manually.' Is there any way of setting up SMTP relay on this dockerized version?

**Comment by iredmail** [comment]
Please read our "Best Practice" tutorial and use `/opt/iredmail/custom/postfix/custom.sh` for advanced customization:
https://docs.iredmail.org/iredmail-easy.best.practice.html
