### ISSUE TITLE
USE_ANTISPAM=NO working?

### ISSUE THREAD

**Issue by fnwirth** [iredmail/dockerized#77]
Dear iredmail team,

I think there might be an  issue with the option USE_ANTISPAM. When I set this to NO (e.g. USE_ANTISPAM=NO) everything works fine at startup. However,  mails are not delivered internally anymore (e.g. from postmaster to postmaster). I havent changed much other things and have verified, that the ANTISPAM option creates this behavior.

A second question would be if the ANTISPAM would also deactivate Anti-Virus, which I think. Can you confirm this?

Thanks for your time.

**Comment by iredmail** [comment]
> mails are not delivered internally anymore

What's the original Postfix error message? I need this for troubleshooting.

> A second question would be if the ANTISPAM would also deactivate Anti-Virus, which I think. Can you confirm this?

With `USE_ANTISPAM=NO`, virus scanning is also DISABLED.

**Comment by fnwirth** [comment]
I see the messages below in /var/log/mail[.]log. However, I do not get an error message while sending the e-mail with Thunderbird.

```
p 14 14:54:10 mail postfix/submission/smtpd[973]: connect from unknown[172.17.0.1]
Sep 14 14:54:10 mail postfix/submission/smtpd[973]: Anonymous TLS connection established from unknown[172.17.0.1]: TLSv1.3 with cipher TLS_AES_128_GCM_SHA256 (128/128 bits) key-exchange X25519 server-signature RSA-PSS (4096 bits)
Sep 14 14:54:10 mail postfix/trivial-rewrite[978]: warning: do not list domain easysmpc.org in BOTH mydestination and virtual_mailbox_domains
Sep 14 14:54:10 mail postfix/trivial-rewrite[978]: warning: do not list domain easysmpc.org in BOTH mydestination and virtual_mailbox_domains
Sep 14 14:54:10 mail postfix/submission/smtpd[973]: 4H85w25t3xz1Yt: client=unknown[172.17.0.1], sasl_method=PLAIN, sasl_username=postmaster@easysmpc.org
Sep 14 14:54:10 mail postfix/cleanup[979]: 4H85w25t3xz1Yt: message-id=<3a66a5bb-193f-8151-4da0-14e2c8260e88@easysmpc.org>
Sep 14 14:54:10 mail postfix/qmgr[896]: 4H85w25t3xz1Yt: from=<postmaster@easysmpc.org>, size=595, nrcpt=1 (queue active)
Sep 14 14:54:10 mail postfix/submission/smtpd[973]: disconnect from unknown[172.17.0.1] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Sep 14 14:54:10 mail postfix/amavis/smtp[980]: connect to 127.0.0.1[127.0.0.1]:10026: Connection refused
Sep 14 14:54:10 mail postfix/amavis/smtp[980]: 4H85w25t3xz1Yt: to=<postmaster@easysmpc.org>, relay=none, delay=0.07, delays=0.05/0.02/0/0, dsn=4.4.1, status=deferred (connect to 127.0.0.1[127.0.0.1]:10026: Connection refused)

```

**Comment by iredmail** [comment]
FYI: https://docs.iredmail.org/errors.html#warning-do-not-list-domain-mydomaincom-in-both-mydestination-and-virtual_mailbox_domains

**Comment by fnwirth** [comment]
Thank you for pointing this out. After correcting the hostname environment variable I saw another error message in the postifx log

```
Sep 17 11:50:24 4f799d5d983a postfix/qmgr[633]: 4H9sZr2pL9z2qx: from=<root@4f799d5d983a>, size=7767, nrcpt=1 (queue active)
Sep 17 11:50:24 4f799d5d983a postfix/amavis/smtp[1469]: connect to 127.0.0.1[127.0.0.1]:10026: Connection refused
Sep 17 11:50:24 4f799d5d983a postfix/amavis/smtp[1469]: 4H9sZr2pL9z2qx: to=<postmaster@mymail.org>, relay=none, delay=300, delays=300/0.03/0/0, dsn=4.4.1, status=deferred (connect to 127.0.0.1[127.0.0.1]:10026: Connection refused)
```

After complete deactivtion as described [here](https://docs.iredmail.org/completely.disable.amavisd.clamav.spamassassin.html) it worked

**Comment by iredmail** [comment]
> connect to 127.0.0.1[127.0.0.1]:10026: Connection refused

With `USE_ANTISPAM=NO`, Postfix config file `/etc/postfix/main.cf` should not have parameter `content_filter = `, and `/etc/postfix/master.cf` should not contain any `content_filter=...:10026` lines. Does your system have any `content_filter` parameter in these 2 files?

If no (which is correct and expected), then those email messages may be stacked in queue BEFORE you set `USE_ANTISPAM=NO`, because Postfix wrote the mail flow related info in queued message file (`/var/spool/postfix/<queue-dir>`).

**Comment by fnwirth** [comment]
My iredmail-docker.conf:
```
HOSTNAME=mail.easysmpc.org
FIRST_MAIL_DOMAIN=easysmpc.org
FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=12345
MLMMJADMIN_API_TOKEN=12345
ROUNDCUBE_DES_KEY=12345
USE_IREDAPD=NO
USE_ANTISPAM=NO
USE_FAIL2BAN=NO
USE_ROUNDCUBE=NO
USE_IREDADMIN=NO
```

My docker run:
```docker run ^
    --rm ^
    --name iredmail ^
    --env-file iredmail-docker.conf ^
    -p 80:80 ^
    -p 443:443 ^
    -p 110:110 ^
    -p 995:995 ^
    -p 143:143 ^
    -p 993:993 ^
    -p 25:25 ^
    -p 465:465 ^
    -p 587:587 ^
    iredmail/mariadb:stable
```
I still find the `content_filter = ` in the tow mentioned files

**Comment by iredmail** [comment]
> I still find the `content_filter = ` in the tow mentioned files

What's the full `content_filter =` lines?

**Comment by fnwirth** [comment]
`root@2dceb3de7b7e:/# cat /etc/postfix/main.cf | grep "content_filter ="`
results in:
`content_filter = smtp-amavis:[127.0.0.1]:10024`

``root@2dceb3de7b7e:/# cat /etc/postfix/master.cf | grep "content_filter"
results in:
```root@2dceb3de7b7e:/# cat /etc/postfix/master.cf | grep "content_filter"
    -o content_filter=smtp-amavis:[127.0.0.1]:10026
    -o content_filter=smtp-amavis:[127.0.0.1]:10026
    -o content_filter=smtp-amavis:[127.0.0.1]:10026
    -o content_filter=
    -o content_filter=
```
