### ISSUE TITLE
Support for Arm64v8

### ISSUE THREAD

**Issue by blaazetech** [iredmail/dockerized#78]
Hi Zhang,

Am trying to use this on a docker setup on ARM server, but its giving me following error, will be looking forward for the support on ARM infrastructure also
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested standard_init_linux.go:228: exec user process caused: exec format error
```

Thanks

**Comment by iredmail** [comment]
No plan for ARM platform shortly, sorry. But it should be easy to build your own image on ARM with files in this repository. :)
