### ISSUE TITLE
Permanently disable certain services?

### ISSUE THREAD

**Issue by ryan77627** [iredmail/dockerized#79]
Hello,

Is there any container agnostic way to disable a service? I'm looking to disable clamav as my server doesn't have enough memory to load the database in memory. I know I could just `docker exec` into the container and remove the symlink to clamav in `/etc/supervisor/conf.d`, however if I rebuild the container to update everything, this change will get reset.

**Comment by iredmail** [comment]
Did you try to mount an empty file as `/etc/supervisor/conf.d/<service>` to disable it?

**Comment by ryan77627** [comment]
I tried symlinking the file to /dev/null, however it got overwritten. So I had to mount as :ro to get it to be persistent. Thanks!
