### ISSUE TITLE
Mail delivery Slow

### ISSUE THREAD

**Issue by arunodhayam10d** [iredmail/dockerized#83]
I have installed iRedmail server using docker. I have given the FQDN for the mail server and the setup is fully done. But while sending the message to another user it is very slow.

Example
test@domain.com sends the message to test@gmail.com, this message becomes delayed. Not only the Gmail others like test@domain1.com, test@domain2.com.

**Comment by iredmail** [comment]
Please paste related postfix log lines for troubleshooting.

**Comment by arunodhayam10d** [comment]
Thanks, ur kind help @iredmail Now it's working fine.
