### ISSUE TITLE
arm64 container 

### ISSUE THREAD

**Issue by NikolayDachev** [iredmail/dockerized#94]
Any plans for official iredmail ARM64/AARCH64 container.

I'm using my own from 2 years without issue :) .. however it is still 2 years old iredmail version 
ROCKPro64 - debian9 aarch64

**Comment by iredmail** [comment]
No plan for an arm edition, sorry. But feel free to build your own image with files in this repo. :)

**Comment by NikolayDachev** [comment]
Thank you!
