### ISSUE TITLE
Cannot overcome Maximum allowed file size is 2.0 MB

### ISSUE THREAD

**Issue by T-helper** [iredmail/dockerized#98]
Recently faced with restriction for max allowed attachments in roudncube.
Does anybody know how to fix it ?

**Comment by iredmail** [comment]
@T-helper Did you check our tutorial here? https://docs.iredmail.org/change.mail.attachment.size.html

**Comment by T-helper** [comment]
@iredmail Yep, i tried all steps from this tutorial, no results. Actually i can attach and sending emails by desktop clients as well, with no restrictions, but roundcube not allowing me to do that, says that there is limit only for 2 mb for uploading. And i've cheked twice php.ini, roundcube config in container, even modified .htaccess, no results. It looks like roundcube or nginx doesent respect this changes

**Comment by iredmail** [comment]
What's the value of parameter `max_message_size` in file `/opt/www/roundcubemail-1.5.2/config/config.inc.php`?
```
$config['max_message_size'] = '50M';
```

**Comment by T-helper** [comment]
@iredmail  my max_message_size is the same as a default, 50M
finally i've solve this, it seems like my php-fpm doesen't have been reloaded propetly or something else, but after tuning 
upload_max_filesize and post_max_size again, it works now. It would be great to have oportunity to set them via enviroments
